experimental_monorepo_root = true

[settings]
auto_install = true

[tools]
# -----------------------------------------------------------------------------
act = "latest"
#gh = "latest"
# -----------------------------------------------------------------------------
npm = "11.6.0"
node = "22"

# -----------------------------------------------------------------------------
[tasks."setup"]
description = "Setup project workspace"
run = [
  "mise //packages/core:setup"
]

[tasks."build"]
description = "Build project artifacts"
run = [
  "mise //packages/core:build"
]

# -----------------------------------------------------------------------------
[tasks."server:start"]
description = "Start server"
run = [
  "mise //packages/core:server:start"
]

# -----------------------------------------------------------------------------
[tasks."storybook:start"]
description = "Start storybook"
run = [
  "mise //packages/core:storybook:start"
]

# -----------------------------------------------------------------------------
[tasks.'github:workflow']
description = "Access to GitHub Actions workflow of the package"
dir = "{{cwd}}"
run = [
  "mise //packages/core:github:workflow"
]

[tasks.'github:workflow:validate']
description = "Validate GitHub Actions workflow of the package"
run = [
  "mise //packages/core:github:workflow:validate"
]
